name: Deploy to Azure Static Web Apps

on:
  push:
    branches:
      - main  # Cambia esto si trabajas en otra rama

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Asegúrate de usar la versión apropiada de Node.js

    - name: Install dependencies
      run: npm install --force
      
    - name: Build the Angular app
      run: npm run build --prod
      
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v0.0.1-preview
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_MANGO_PEBBLE_091BBAA0F }} # Necesitas añadir este secreto a tu repositorio
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_path: "dist" 
        api_location: "" 
